version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: r2000-go
    ports:
      - 3000:3000
    volumes:
      - ..:/app

    command: sleep infinity
